#!/bin/bash
########################################
# Set environment variables
########################################

export GOPATH=`pwd`

########################################
# Get dependency projects
########################################

dependencies=(
"github.com/antlr/antlr4/runtime/Go/antlr"
)

go get "${dependencies[@]}"

########################################
# Get latest source codes
########################################

git pull

go_usql_path="github.com/cybergarage/usql-go/usql"
go_usql_dir="src/${go_usql_path}"
if [ -d ${go_usql_dir} ]; then
  pushd ${go_usql_dir} && git pull && popd
else
  go get -u ${go_usql_path}
fi
