#!/bin/bash
export GOPATH=`pwd`

git pull

go_usql_path="github.com/cybergarage/usql-go/usql"
go_usql_dir="src/${go_usql_path}"
if [ -d ${go_usql_dir} ]; then
  pushd ${go_usql_dir} && git pull && popd
else
  go get -u ${go_usql_path}
fi
