CREATE DATABASE benchbase;
DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS new_order;
DROP TABLE IF EXISTS order_line;
DROP TABLE IF EXISTS oorder;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS district;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS warehouse;
CREATE TABLE  warehouse (w_id INT, w_ytd , w_tax , w_name VARCHAR(10), w_street_1 VARCHAR(20), w_street_2 VARCHAR(20), w_city VARCHAR(20), w_state CHAR(2), w_zip CHAR(9), PRIMARY KEY (w_id));
CREATE TABLE  item (i_id INT, i_name VARCHAR(24), i_price , i_data VARCHAR(50), i_im_id INT, PRIMARY KEY (i_id));
CREATE TABLE  stock (s_w_id INT, s_i_id INT, s_quantity INT, s_ytd , s_order_cnt INT, s_remote_cnt INT, s_data VARCHAR(50), s_dist_01 CHAR(24), s_dist_02 CHAR(24), s_dist_03 CHAR(24), s_dist_04 CHAR(24), s_dist_05 CHAR(24), s_dist_06 CHAR(24), s_dist_07 CHAR(24), s_dist_08 CHAR(24), s_dist_09 CHAR(24), s_dist_10 CHAR(24), PRIMARY KEY (s_w_id, s_i_id));
CREATE TABLE  district (d_w_id INT, d_id INT, d_ytd , d_tax , d_next_o_id INT, d_name VARCHAR(10), d_street_1 VARCHAR(20), d_street_2 VARCHAR(20), d_city VARCHAR(20), d_state CHAR(2), d_zip CHAR(9), PRIMARY KEY (d_w_id, d_id));
CREATE TABLE  customer (c_w_id INT, c_d_id INT, c_id INT, c_discount , c_credit CHAR(2), c_last VARCHAR(16), c_first VARCHAR(16), c_credit_lim , c_balance , c_ytd_payment FLOAT, c_payment_cnt INT, c_delivery_cnt INT, c_street_1 VARCHAR(20), c_street_2 VARCHAR(20), c_city VARCHAR(20), c_state CHAR(2), c_zip CHAR(9), c_phone CHAR(16), c_since TIMESTAMP, c_middle CHAR(2), c_data VARCHAR(500), PRIMARY KEY (c_w_id, c_d_id, c_id));
CREATE TABLE  history (h_c_id INT, h_c_d_id INT, h_c_w_id INT, h_d_id INT, h_w_id INT, h_date TIMESTAMP, h_amount , h_data VARCHAR(24));
CREATE TABLE  oorder (o_w_id INT, o_d_id INT, o_id INT, o_c_id INT, o_carrier_id INT, o_ol_cnt INT, o_all_local INT, o_entry_d TIMESTAMP, PRIMARY KEY (o_w_id, o_d_id, o_id));
CREATE TABLE  new_order (no_w_id INT, no_d_id INT, no_o_id INT, PRIMARY KEY (no_w_id, no_d_id, no_o_id));
CREATE TABLE  order_line (ol_w_id INT, ol_d_id INT, ol_o_id INT, ol_number INT, ol_i_id INT, ol_delivery_d TIMESTAMP, ol_amount , ol_supply_w_id INT, ol_quantity , ol_dist_info CHAR(24), PRIMARY KEY (ol_w_id, ol_d_id, ol_o_id, ol_number));
ALTER TABLE customer ADD INDEX idx_customer_name (c_w_id, c_d_id, c_last, c_first);
SELECT CURRENT_SCHEMA() FROM;